// <auto-generated />
namespace PlanesTour.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMissedReferences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMissedReferences));
        
        string IMigrationMetadata.Id
        {
            get { return "201602160022555_AddMissedReferences"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
